server:
  port: 8011

spring:
  datasource:
    url: jdbc:h2:file:./.data/${spring.application.name}-db
    username: root
    password: 5939523
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9000,localhost:19092
    consumer:
      group-id: organization

application:
  organization: organization-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:8004/api/v2/spans
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      group:
        all:
          include: "*"
      show-details: always
      show-components: always
  health:
    circuit-breakers:
      enabled: true

resilience4j:
  circuit-breaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
    instances:
      getCouriers:
        base-config: default

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
