server:
  port: 8010

spring:
  r2dbc:
    url: r2dbc:h2:file:///./data/db
    username: root
    password: 5939523
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8000/eureka
