server:
  port: 8003

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:h2:file:./.data/${spring.application.name}-db
    username: root
    password: 5939523
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      separator: ;;

  security:
    oauth2:
      authorization-server:
        client:
          organization-service:
            registration:
              client-id: organization-service
              client-secret: "{noop}organization-service-secret"
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
            token:
              access-token-time-to-live: 3600s
              refresh-token-time-to-live: 7200s
          courier-service:
            registration:
              client-id: courier-service
              client-secret: "{noop}courier-service-secret"
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
            token:
              access-token-time-to-live: 3600s
              refresh-token-time-to-live: 7200s
